### PR TITLE
Add ability to change db path from CLI

### PR DESCRIPTION
**Pull request by mxstbr**
cc @developit, does this fit your needs?

### CODE REVIEW

**Comment by developit** [comment]
Might actually be easier to use an env var (just a thought).  Either is good though.  Env vars just make it a little simpler in docker (I know I sound like I'm selling docker, not sure why lol)

**Comment by mxstbr** [comment]
Oh yeah that actually makes the implementation way easier too, good call!

**Comment by mxstbr** [comment]
Switched to using `process.env.DB_PATH`. Whatcha think?

**Comment by developit** [comment]
Works for me! 👍

**Pull request merged**
